# Generated by Django 3.1.5 on 2021-01-19 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('nacionalidad', models.CharField(max_length=20, verbose_name='Nacionalidad')),
                ('edad', models.PositiveIntegerField(default=0, verbose_name='Edad')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField(verbose_name='Fecha del prestamo')),
                ('fecha_devolucion', models.DateField(blank=True, null=True, verbose_name='Fecha de la devolución')),
                ('devuelto', models.BooleanField(default=False, verbose_name='Regresado')),
                ('lector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lector.lector', verbose_name='Lector')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libro.libro', verbose_name='Libro')),
            ],
        ),
    ]
